global:
  scrape_interval: 15s  # Intervalle de collecte des métriques

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.1.13:8080']  # IP et port de Jenkins
