global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jenkins'
    metrics_path: /prometheus
    static_configs:
      - targets: ['192.168.33.10:8080']  # Jenkins URL

  - job_name: 'mysqldb'
    metrics_path: /metrics
    static_configs:
      - targets: [ '192.168.33.10:9104' ]  # Replace with your actual IP and the MySQL Exporter port


  - job_name: 'spring-app'
    metrics_path: /tpFoyer17/actuator/prometheus  # Adjust to match your endpoint
    static_configs:
      - targets: [ '172.18.0.3:8287' ]  # Replace with the actual IP and port


  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']  # Docker daemon metrics (if enabled)
